"""add user, resep, menu_makan

Revision ID: 2bf2d4ab08f5
Revises: c1de3c231a9c
Create Date: 2025-05-26 16:06:55.164512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf2d4ab08f5'
down_revision = 'c1de3c231a9c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_resep', sa.String(length=100), nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=True),
    sa.Column('gambar', sa.String(length=255), nullable=True),
    sa.Column('bahan', sa.Text(), nullable=True),
    sa.Column('langkah', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resep'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('menu_makan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hari', sa.String(length=20), nullable=False),
    sa.Column('waktu_makan', sa.String(length=20), nullable=False),
    sa.Column('resep_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resep_id'], ['resep.id'], name=op.f('fk_menu_makan_resep_id_resep')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_menu_makan_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_makan'))
    )
    op.drop_index(op.f('my_index'), table_name='models')
    op.drop_table('models')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models'))
    )
    op.create_index(op.f('my_index'), 'models', ['name'], unique=True)
    op.drop_table('menu_makan')
    op.drop_table('users')
    op.drop_table('resep')
    # ### end Alembic commands ###
