"""init

Revision ID: 8ac1aa9732c3
Revises: 
Create Date: 2025-06-02 22:39:15.130332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac1aa9732c3'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models'))
    )
    op.create_index('my_index', 'models', ['name'], unique=True, mysql_length=255)
    op.create_table('reseps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_resep', sa.Text(), nullable=False),
    sa.Column('bahan', sa.Text(), nullable=False),
    sa.Column('langkah_memasak', sa.Text(), nullable=False),
    sa.Column('gambar', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reseps'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('menu_makans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hari', sa.String(length=20), nullable=False),
    sa.Column('waktu_makan', sa.String(length=20), nullable=False),
    sa.Column('resep_id', sa.Integer(), nullable=False),
    sa.Column('gambar', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['resep_id'], ['reseps.id'], name=op.f('fk_menu_makans_resep_id_reseps')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_menu_makans_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_makans'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_makans')
    op.drop_table('users')
    op.drop_table('reseps')
    op.drop_index('my_index', table_name='models', mysql_length=255)
    op.drop_table('models')
    # ### end Alembic commands ###
